# Generated by Django 3.2 on 2022-06-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('chatroom_id', models.AutoField(db_column='chatroom_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=145)),
            ],
        ),
    ]
