# Generated by Django 3.2 on 2022-06-19 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0003_auto_20220618_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
