# Generated by Django 3.2 on 2022-06-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0004_chatroom_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='subject',
            field=models.CharField(max_length=445),
        ),
    ]
